import json
import os

overrides = {}
if os.path.exists("overrides.json"):
    with open("overrides.json", "r", encoding="utf-8") as f:
        overrides = json.load(f)

raw_chunks = [
"""{ "University of Wisconsin-Madison": {"test_policy": "Optional", "has_ed": false, "has_ea": true, "has_rea": false, "ed_deadline": null, "ea_deadline": "11/01", "rea_deadline": null}, "Tulane University": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/10", "rea_deadline": null}, "University of Illinois Urbana-Champaign": {"test_policy": "Optional", "has_ed": false, "has_ea": true, "has_rea": false, "ed_deadline": null, "ea_deadline": "11/01", "rea_deadline": null}, "Purdue University": {"test_policy": "Required", "has_ed": false, "has_ea": true, "has_rea": false, "ed_deadline": null, "ea_deadline": "11/01", "rea_deadline": null}, "Ohio State University": {"test_policy": "Required", "has_ed": false, "has_ea": true, "has_rea": false, "ed_deadline": null, "ea_deadline": "11/01", "rea_deadline": null}, "Pennsylvania State University": {"test_policy": "Optional", "has_ed": false, "has_ea": true, "has_rea": false, "ed_deadline": null, "ea_deadline": "11/01", "rea_deadline": null}, "Texas A&M University": {"test_policy": "Optional", "has_ed": false, "has_ea": false, "has_rea": false, "ed_deadline": null, "ea_deadline": null, "rea_deadline": null}, "University of Texas at Austin": {"test_policy": "Required", "has_ed": false, "has_ea": true, "has_rea": false, "ed_deadline": null, "ea_deadline": "10/15", "rea_deadline": null}, "Indiana University Bloomington": {"test_policy": null, "has_ed": false, "has_ea": true, "has_rea": false, "ed_deadline": null, "ea_deadline": "11/01", "rea_deadline": null}, "University of Washington": {"test_policy": null, "has_ed": false, "has_ea": false, "has_rea": false, "ed_deadline": null, "ea_deadline": null, "rea_deadline": null} }""",
"""{ "Michigan State University": {"test_policy": "Required", "has_ed": false, "has_ea": true, "has_rea": false, "ed_deadline": null, "ea_deadline": "11/01", "rea_deadline": null}, "Virginia Tech": {"test_policy": "Optional", "has_ed": false, "has_ea": true, "has_rea": false, "ed_deadline": null, "ea_deadline": "11/01", "rea_deadline": null}, "Case Western Reserve University": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/01", "rea_deadline": null}, "University of Maryland, College Park": {"test_policy": "Required", "has_ed": false, "has_ea": true, "has_rea": false, "ed_deadline": null, "ea_deadline": "11/01", "rea_deadline": null}, "Boston University": {"test_policy": "Optional", "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": null, "rea_deadline": null}, "Rensselaer Polytechnic Institute": {"test_policy": null, "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "12/01", "rea_deadline": null}, "University of Pittsburgh": {"test_policy": null, "has_ed": false, "has_ea": false, "has_rea": false, "ed_deadline": null, "ea_deadline": null, "rea_deadline": null}, "Florida State University": {"test_policy": "Required", "has_ed": false, "has_ea": true, "has_rea": false, "ed_deadline": null, "ea_deadline": "10/15", "rea_deadline": null}, "Villanova University": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/01", "rea_deadline": null}, "Stony Brook University": {"test_policy": null, "has_ed": false, "has_ea": true, "has_rea": false, "ed_deadline": null, "ea_deadline": "11/01", "rea_deadline": null} }""",
"""{ "University of Massachusetts Amherst": {"test_policy": "Optional", "has_ed": false, "has_ea": true, "has_rea": false, "ed_deadline": null, "ea_deadline": "11/05", "rea_deadline": null}, "North Carolina State University": {"test_policy": null, "has_ed": false, "has_ea": true, "has_rea": false, "ed_deadline": null, "ea_deadline": "11/01", "rea_deadline": null}, "University of California, Merced": {"test_policy": null, "has_ed": false, "has_ea": false, "has_rea": false, "ed_deadline": null, "ea_deadline": null, "rea_deadline": null}, "Brandeis University": {"test_policy": "Optional", "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": null, "rea_deadline": null}, "George Washington University": {"test_policy": "Optional", "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": null, "rea_deadline": null}, "Fordham University": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/01", "rea_deadline": null}, "University of Miami": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/01", "rea_deadline": null}, "Syracuse University": {"test_policy": null, "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": null, "rea_deadline": null}, "Stevens Institute of Technology": {"test_policy": "Optional", "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": null, "rea_deadline": null}, "University of Connecticut": {"test_policy": "Optional", "has_ed": false, "has_ea": false, "has_rea": false, "ed_deadline": null, "ea_deadline": null, "rea_deadline": null} }""",
"""{ "United States Naval Academy": {"test_policy": null, "has_ed": false, "has_ea": false, "has_rea": false, "ed_deadline": null, "ea_deadline": null, "rea_deadline": null}, "United States Military Academy": {"test_policy": null, "has_ed": false, "has_ea": false, "has_rea": false, "ed_deadline": null, "ea_deadline": null, "rea_deadline": null}, "Haverford College": {"test_policy": "Optional", "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": null, "rea_deadline": null}, "Barnard College": {"test_policy": "Optional", "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": null, "rea_deadline": null}, "College of the Holy Cross": {"test_policy": "Optional", "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": null, "rea_deadline": null}, "Bates College": {"test_policy": "Optional", "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": null, "rea_deadline": null}, "Grinnell College": {"test_policy": null, "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": null, "rea_deadline": null}, "Occidental College": {"test_policy": "Optional", "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": null, "rea_deadline": null}, "Kenyon College": {"test_policy": "Optional", "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": null, "rea_deadline": null}, "Colorado College": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/01", "rea_deadline": null} }""",
"""{ "Mount Holyoke College": {"test_policy": "Optional", "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": null, "rea_deadline": null}, "Trinity College": {"test_policy": null, "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": null, "rea_deadline": null}, "University of Richmond": {"test_policy": null, "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/01", "rea_deadline": null}, "Furman University": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/01", "rea_deadline": null}, "Denison University": {"test_policy": "Optional", "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": null, "rea_deadline": null}, "Dickinson College": {"test_policy": "Optional", "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": null, "rea_deadline": null}, "Scripps College": {"test_policy": "Optional", "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": null, "rea_deadline": null}, "St. Olaf College": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/01", "rea_deadline": null}, "Bryn Mawr College": {"test_policy": "Optional", "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": null, "rea_deadline": null}, "Bucknell University": {"test_policy": null, "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": null, "rea_deadline": null} }""",
"""{ "Lafayette College": {"test_policy": "Optional", "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": null, "rea_deadline": null}, "Skidmore College": {"test_policy": null, "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": null, "rea_deadline": null}, "Union College": {"test_policy": null, "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/01", "rea_deadline": null}, "Whitman College": {"test_policy": "Optional", "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": null, "rea_deadline": null}, "Oberlin College": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/01", "rea_deadline": null}, "Reed College": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/01", "rea_deadline": null}, "Macalester College": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/01", "rea_deadline": null}, "Connecticut College": {"test_policy": "Optional", "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": null, "rea_deadline": null}, "Muhlenberg College": {"test_policy": null, "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": "12/01", "rea_deadline": null}, "Franklin & Marshall College": {"test_policy": "Optional", "has_ed": true, "has_ea": false, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": null, "rea_deadline": null} }""",
"""{ "Gettysburg College": {"test_policy": "Required", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": "12/01", "rea_deadline": null}, "Lawrence University": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/01", "rea_deadline": null}, "Rhodes College": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/15", "rea_deadline": null}, "DePauw University": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/01", "rea_deadline": null}, "Wabash College": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": "12/01", "rea_deadline": null}, "Centre College": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/15", "rea_deadline": null}, "Allegheny College": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "12/01", "rea_deadline": null}, "Earlham College": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": "11/15", "rea_deadline": null}, "Wofford College": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/15", "rea_deadline": null}, "Hobart and William Smith Colleges": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": "11/15", "rea_deadline": null} }""",
"""{ "Clemson University": {"test_policy": "Optional", "has_ed": false, "has_ea": true, "has_rea": false, "ed_deadline": null, "ea_deadline": "10/15", "rea_deadline": null}, "University of California, Davis": {"test_policy": null, "has_ed": false, "has_ea": false, "has_rea": false, "ed_deadline": null, "ea_deadline": null, "rea_deadline": null}, "University of California, San Diego": {"test_policy": null, "has_ed": false, "has_ea": false, "has_rea": false, "ed_deadline": null, "ea_deadline": null, "rea_deadline": null}, "University of California, Irvine": {"test_policy": null, "has_ed": false, "has_ea": false, "has_rea": false, "ed_deadline": null, "ea_deadline": null, "rea_deadline": null}, "New Jersey Institute of Technology": {"test_policy": null, "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": "12/15", "rea_deadline": null}, "Drexel University": {"test_policy": null, "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/15", "ea_deadline": "11/15", "rea_deadline": null}, "Colorado School of Mines": {"test_policy": "Optional", "has_ed": false, "has_ea": true, "has_rea": false, "ed_deadline": null, "ea_deadline": "11/01", "rea_deadline": null}, "Santa Clara University": {"test_policy": "Optional", "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/01", "rea_deadline": null}, "Marquette University": {"test_policy": "Optional", "has_ed": false, "has_ea": true, "has_rea": false, "ed_deadline": null, "ea_deadline": "11/15", "rea_deadline": null}, "Pepperdine University": {"test_policy": null, "has_ed": true, "has_ea": true, "has_rea": false, "ed_deadline": "11/01", "ea_deadline": "11/01", "rea_deadline": null} }"""
]

for c in raw_chunks:
    try:
        parsed = json.loads(c)
        overrides.update(parsed)
    except Exception as e:
        print(e)
        
with open("overrides.json", "w", encoding="utf-8") as f:
    json.dump(overrides, f, indent=4)
print(f"Total overrides now: {len(overrides)}")
