# college_lists.py
# US News 2024-2025 Rankings
# school name + state are used to look up College Scorecard data

NATIONAL_UNIVERSITIES = [
    {"name": "Princeton University",                          "state": "NJ"},
    {"name": "Massachusetts Institute of Technology",         "state": "MA"},
    {"name": "Harvard University",                            "state": "MA"},
    {"name": "Stanford University",                           "state": "CA"},
    {"name": "Yale University",                               "state": "CT"},
    {"name": "University of Chicago",                         "state": "IL"},
    {"name": "Johns Hopkins University",                      "state": "MD"},
    {"name": "University of Pennsylvania",                    "state": "PA"},
    {"name": "California Institute of Technology",            "state": "CA"},
    {"name": "Duke University",                               "state": "NC"},
    {"name": "Dartmouth College",                             "state": "NH"},
    {"name": "Northwestern University",                       "state": "IL"},
    {"name": "Brown University",                              "state": "RI"},
    {"name": "Vanderbilt University",                         "state": "TN"},
    {"name": "Columbia University",                           "state": "NY"},
    {"name": "Cornell University",                            "state": "NY"},
    {"name": "Rice University",                               "state": "TX"},
    {"name": "Washington University in St. Louis",            "state": "MO"},
    {"name": "University of Notre Dame",                      "state": "IN"},
    {"name": "University of California, Los Angeles",         "state": "CA"},
    {"name": "Emory University",                              "state": "GA"},
    {"name": "University of California, Berkeley",            "state": "CA"},
    {"name": "Georgetown University",                         "state": "DC"},
    {"name": "Carnegie Mellon University",                    "state": "PA"},
    {"name": "University of Michigan-Ann Arbor",              "state": "MI"},
    {"name": "University of North Carolina at Chapel Hill",   "state": "NC"},
    {"name": "University of Virginia",                        "state": "VA"},
    {"name": "University of Southern California",             "state": "CA"},
    {"name": "Tufts University",                              "state": "MA"},
    {"name": "New York University",                           "state": "NY"},
    {"name": "University of California, Santa Barbara",       "state": "CA"},
    {"name": "University of Florida",                         "state": "FL"},
    {"name": "University of Rochester",                       "state": "NY"},
    {"name": "Boston College",                                "state": "MA"},
    {"name": "Wake Forest University",                        "state": "NC"},
    {"name": "Lehigh University",                             "state": "PA"},
    {"name": "Northeastern University",                       "state": "MA"},
    {"name": "William & Mary",                                "state": "VA"},
    {"name": "University of Georgia",                         "state": "GA"},
    {"name": "University of Wisconsin-Madison",               "state": "WI"},
    {"name": "Tulane University",                             "state": "LA"},
    {"name": "University of Illinois Urbana-Champaign",       "state": "IL"},
    {"name": "Purdue University",                             "state": "IN"},
    {"name": "Ohio State University",                         "state": "OH"},
    {"name": "Pennsylvania State University",                 "state": "PA"},
    {"name": "Texas A&M University",                          "state": "TX"},
    {"name": "University of Texas at Austin",                 "state": "TX"},
    {"name": "Indiana University Bloomington",                "state": "IN"},
    {"name": "University of Washington",                      "state": "WA"},
    {"name": "Michigan State University",                     "state": "MI"},
    {"name": "University of Maryland, College Park",          "state": "MD"},
    {"name": "Boston University",                             "state": "MA"},
    {"name": "Case Western Reserve University",               "state": "OH"},
    {"name": "Rensselaer Polytechnic Institute",              "state": "NY"},
    {"name": "University of Pittsburgh",                      "state": "PA"},
    {"name": "Florida State University",                      "state": "FL"},
    {"name": "Villanova University",                          "state": "PA"},
    {"name": "Santa Clara University",                        "state": "CA"},
    {"name": "George Washington University",                  "state": "DC"},
    {"name": "Fordham University",                            "state": "NY"},
    {"name": "University of Miami",                           "state": "FL"},
    {"name": "Syracuse University",                           "state": "NY"},
    {"name": "Stevens Institute of Technology",               "state": "NJ"},
    {"name": "University of Connecticut",                     "state": "CT"},
    {"name": "Clemson University",                            "state": "SC"},
    {"name": "University of California, Davis",               "state": "CA"},
    {"name": "University of California, San Diego",           "state": "CA"},
    {"name": "University of California, Irvine",              "state": "CA"},
    {"name": "Marquette University",                          "state": "WI"},
    {"name": "American University",                           "state": "DC"},
    {"name": "Pepperdine University",                         "state": "CA"},
    {"name": "University of Denver",                          "state": "CO"},
    {"name": "Baylor University",                             "state": "TX"},
    {"name": "Loyola University Chicago",                     "state": "IL"},
    {"name": "Texas Christian University",                    "state": "TX"},
    {"name": "University of Minnesota Twin Cities",           "state": "MN"},
    {"name": "Virginia Tech",                                 "state": "VA"},
    {"name": "Rutgers University-New Brunswick",              "state": "NJ"},
    {"name": "University of Iowa",                            "state": "IA"},
    {"name": "University of Alabama",                         "state": "AL"},
    {"name": "Brigham Young University",                      "state": "UT"},
    {"name": "University of Missouri",                        "state": "MO"},
    {"name": "University of Colorado Boulder",                "state": "CO"},
    {"name": "Arizona State University",                      "state": "AZ"},
    {"name": "University of Arizona",                         "state": "AZ"},
    {"name": "Howard University",                             "state": "DC"},
    {"name": "University of Vermont",                         "state": "VT"},
    {"name": "Worcester Polytechnic Institute",               "state": "MA"},
    {"name": "Stony Brook University",                        "state": "NY"},
    {"name": "University at Buffalo",                         "state": "NY"},
    {"name": "University of Oregon",                          "state": "OR"},
    {"name": "Colorado State University",                     "state": "CO"},
    {"name": "University of Utah",                            "state": "UT"},
    {"name": "Drexel University",                             "state": "PA"},
    {"name": "Colorado School of Mines",                      "state": "CO"},
    {"name": "University of Delaware",                        "state": "DE"},
    {"name": "Seton Hall University",                         "state": "NJ"},
    {"name": "James Madison University",                      "state": "VA"},
    {"name": "University of Tennessee",                       "state": "TN"},
    {"name": "University of South Carolina",                  "state": "SC"},
    {"name": "Yeshiva University",                            "state": "NY"},
]

LIBERAL_ARTS_COLLEGES = [
    {"name": "Williams College",                              "state": "MA"},
    {"name": "Amherst College",                               "state": "MA"},
    {"name": "Swarthmore College",                            "state": "PA"},
    {"name": "Pomona College",                                "state": "CA"},
    {"name": "Wellesley College",                             "state": "MA"},
    {"name": "Bowdoin College",                               "state": "ME"},
    {"name": "Carleton College",                              "state": "MN"},
    {"name": "Middlebury College",                            "state": "VT"},
    {"name": "Claremont McKenna College",                     "state": "CA"},
    {"name": "Davidson College",                              "state": "NC"},
    {"name": "Washington and Lee University",                 "state": "VA"},
    {"name": "Colby College",                                 "state": "ME"},
    {"name": "Colgate University",                            "state": "NY"},
    {"name": "Hamilton College",                              "state": "NY"},
    {"name": "Harvey Mudd College",                           "state": "CA"},
    {"name": "Vassar College",                                "state": "NY"},
    {"name": "Smith College",                                 "state": "MA"},
    {"name": "United States Naval Academy",                   "state": "MD"},
    {"name": "United States Military Academy",                "state": "NY"},
    {"name": "Haverford College",                             "state": "PA"},
    {"name": "Barnard College",                               "state": "NY"},
    {"name": "College of the Holy Cross",                     "state": "MA"},
    {"name": "Bates College",                                 "state": "ME"},
    {"name": "Grinnell College",                              "state": "IA"},
    {"name": "Occidental College",                            "state": "CA"},
    {"name": "Kenyon College",                                "state": "OH"},
    {"name": "Colorado College",                              "state": "CO"},
    {"name": "Mount Holyoke College",                         "state": "MA"},
    {"name": "Trinity College",                               "state": "CT"},
    {"name": "University of Richmond",                        "state": "VA"},
    {"name": "Furman University",                             "state": "SC"},
    {"name": "Denison University",                            "state": "OH"},
    {"name": "Dickinson College",                             "state": "PA"},
    {"name": "Scripps College",                               "state": "CA"},
    {"name": "St. Olaf College",                              "state": "MN"},
    {"name": "Bryn Mawr College",                             "state": "PA"},
    {"name": "Bucknell University",                           "state": "PA"},
    {"name": "Lafayette College",                             "state": "PA"},
    {"name": "Skidmore College",                              "state": "NY"},
    {"name": "Union College",                                 "state": "NY"},
    {"name": "Whitman College",                               "state": "WA"},
    {"name": "Oberlin College",                               "state": "OH"},
    {"name": "Reed College",                                  "state": "OR"},
    {"name": "Macalester College",                            "state": "MN"},
    {"name": "Connecticut College",                           "state": "CT"},
    {"name": "Muhlenberg College",                            "state": "PA"},
    {"name": "Franklin & Marshall College",                   "state": "PA"},
    {"name": "Gettysburg College",                            "state": "PA"},
    {"name": "Lawrence University",                           "state": "WI"},
    {"name": "Rhodes College",                                "state": "TN"},
    {"name": "DePauw University",                             "state": "IN"},
    {"name": "Wabash College",                                "state": "IN"},
    {"name": "Centre College",                                "state": "KY"},
    {"name": "Allegheny College",                             "state": "PA"},
    {"name": "Earlham College",                               "state": "IN"},
    {"name": "Wofford College",                               "state": "SC"},
    {"name": "Hobart and William Smith Colleges",             "state": "NY"},
    {"name": "Sewanee: The University of the South",          "state": "TN"},
    {"name": "Augustana College",                             "state": "IL"},
    {"name": "College of Wooster",                            "state": "OH"},
    {"name": "Juniata College",                               "state": "PA"},
    {"name": "Beloit College",                                "state": "WI"},
    {"name": "Gustavus Adolphus College",                     "state": "MN"},
    {"name": "Ohio Wesleyan University",                      "state": "OH"},
    {"name": "Luther College",                                "state": "IA"},
    {"name": "Hope College",                                  "state": "MI"},
    {"name": "Kalamazoo College",                             "state": "MI"},
    {"name": "Hanover College",                               "state": "IN"},
    {"name": "Ripon College",                                 "state": "WI"},
    {"name": "Austin College",                                "state": "TX"},
    {"name": "Agnes Scott College",                           "state": "GA"},
    {"name": "Berea College",                                 "state": "KY"},
    {"name": "University of Puget Sound",                     "state": "WA"},
    {"name": "Hendrix College",                               "state": "AR"},
    {"name": "St. John's College",                            "state": "MD"},
    {"name": "Transylvania University",                       "state": "KY"},
    {"name": "Pitzer College",                                "state": "CA"},
    {"name": "Sarah Lawrence College",                        "state": "NY"},
    {"name": "Illinois Wesleyan University",                  "state": "IL"},
    {"name": "Randolph-Macon College",                        "state": "VA"},
    {"name": "Hampden-Sydney College",                        "state": "VA"},
    {"name": "Morehouse College",                             "state": "GA"},
    {"name": "Spelman College",                               "state": "GA"},
    {"name": "Knox College",                                  "state": "IL"},
    {"name": "Lake Forest College",                           "state": "IL"},
    {"name": "Alma College",                                  "state": "MI"},
    {"name": "Concordia College",                             "state": "MN"},
    {"name": "Willamette University",                         "state": "OR"},
    {"name": "Westminster College",                           "state": "MO"},
    {"name": "Wittenberg University",                         "state": "OH"},
    {"name": "Millsaps College",                              "state": "MS"},
    {"name": "Gordon College",                                "state": "MA"},
    {"name": "Hiram College",                                 "state": "OH"},
    {"name": "Pacific Lutheran University",                   "state": "WA"},
    {"name": "Covenant College",                              "state": "GA"},
    {"name": "Hampden-Sydney College",                        "state": "VA"},
    {"name": "Monmouth College",                              "state": "IL"},
    {"name": "Drew University",                               "state": "NJ"},
    {"name": "Muskingum University",                          "state": "OH"},
    {"name": "Albion College",                                "state": "MI"},
    {"name": "Occidental College",                            "state": "CA"},
]
